## MLOps Assignment 1

Q1. Print multiplication table from 1 to 10

In [1]:
for i in range(1, 11):
    for j in range(1, 11):
        print(f"{i*j}", end='\t')
    print()

1	2	3	4	5	6	7	8	9	10
2	4	6	8	10	12	14	16	18	20
3	6	9	12	15	18	21	24	27	30
4	8	12	16	20	24	28	32	36	40
5	10	15	20	25	30	35	40	45	50
6	12	18	24	30	36	42	48	54	60
7	14	21	28	35	42	49	56	63	70
8	16	24	32	40	48	56	64	72	80
9	18	27	36	45	54	63	72	81	90
10	20	30	40	50	60	70	80	90	100

Q2. Given two lists, l1 and l2, write a program to create a third list l3 by picking an odd-index element from the list l1 and even index elements from the list l2.

In [2]:
l1= [10, 21, 32, 43, 54, 65]
l2= [70, 81, 92, 103, 114, 125]
l3= []
l3.extend([l1[i] for i in range(1, len(l1), 2)])
l3.extend([l2[i] for i in range(0, len(l2), 2)])
print("List l3:", l3)

List l3: [21, 43, 65, 70, 92, 114]

Q3. Print a this pattern(*)

    * * * * * * * *
      * * * * * * *
        * * * * * *
          * * * * *
            * * * *
              * * *
                * *
                  *

In [3]:
n= 8
for i in range(n):
    for j in range(i):
        print(" ", end="")
    for k in range(n-i):
        print("*", end="")
    print()

********
 *******
  ******
   *****
    ****
     ***
      **
       *

Q4. Create a function named `exponent(base, exp)` that returns an integer representing the result of raising `base` to the power of `exp`.
`exp` is >0.

base = 5
exponent = 4

5 raises to the power of 4 is: 625
i.e. (5 *5 * 5 *5 = 625)

In [4]:
base= 5
exp= 4

def exponent(base, exp):
    x= 1
    for i in range(exp):
        x= x*base
    return x
print(exponent(base, exp))

625

Q5. Create a file named test.txt and insert the following content into it.

    line1
    line2
    line3
    line4
    line5
    line6
    line7

Write a program which write all content of a given file (test.txt) into a new file by skipping line number 5 (line5)

In [5]:
content= """line1
line2
line3
line4
line5
line6
line7"""

with open("test.txt", "w") as file:
    file.write(content)
with open("test.txt", "r") as file:
    lines= file.readlines()
with open("new.txt", "w") as new:
    for i, line in enumerate(lines):
        if i!= 4:
            new.write(line)
with open("new.txt", "r") as file:
    content= file.read()

print("Content of 'new.txt':")
print(content)

Content of 'new.txt':
line1
line2
line3
line4
line6
line7

Q6. Write a program which receives three names from the user in a single input() function call.

    Input: IIT JODHPUR RAJASTHAN

    Output:
    IIT
    JODHPUR
    RAJASTHAN

In [6]:
strings= input("Input: ")
names= strings.split()
if len(names)!= 3:
    print("Error: Please enter exactly three names.")
else:
    print("Output:")
    for name in names:
        print(name)

Input: IIT JODHPUR RAJASTHAN
Output:
IIT
JODHPUR
RAJASTHAN

Q7. Write a program to define a function called show_employee() with the following requirements:

*   It should take the employee's name and salary as input and display both.
*   If the salary is not provided in the function call, assign a default value of 9000 to it.

After passing:

showEmployee("Bill Gates", 12000)

showEmployee("Elon Musk")

It should print:

Name: Bill Gates salary: 12000

Name: Elon Musk salary: 9000

In [7]:
def employee(name, salary=9000):
    print(f"Name: {name} salary: {salary}")

name= input("Enter the employee's name: ")
salary_input= input("Enter the employee's salary: ")

if salary_input:
    try:
        salary= int(salary_input)
    except ValueError:
        print("Invalid salary input. Using default salary of 9000.")
        salary= 9000
else:
    salary = 9000

employee(name, salary)

Enter the employee's name: EMPLOYEE
Enter the employee's salary:
Name: EMPLOYEE salary: 9000

Q8. Write a program to identify words that contain both letters and digits from a given input string.

    Given str1 = "Harry25 is Gryffindor Wizard50 and cursed"

    Output:
    Harry25
    Wizard50

In [8]:
import re

def fun(input):
    words= input.split()
    pattern= re.compile(r'^(?=.*[a-zA-Z])(?=.*\d).+$')
    result= [word for word in words if pattern.match(word)]
    return result

string= input("Input: ")

func= fun(string)
print("Output:")
print(func)

Input: Harry25 is Gryffindor Wizard50 and cursed
Output:
['Harry25', 'Wizard50']

Q9. Write a program to substitute each special character in the given string with the symbol #.

    Given: str1 = '/*Modi is @Politician & Melony!!'

    Output: ##Modi is #Politician # Melony##

In [9]:
import re

def fun(input):
    result= re.sub(r'[^\w\s]', '#', input)
    return result

inputstr= input("Input: ")
string= fun(inputstr)
print("Output:")
print(string)

Input: /*Modi is @Politician & Melony!!
Output:
##Modi is #Politician # Melony##

Q10. Construct a Python set that displays elements from both lists as pairs.

    Given:

    first_list = [2, 3, 4, 5, 6, 7, 8]
    second_list = [4, 9, 16, 25, 36, 49, 64]
    Output: Result is  {(6, 36), (8, 64), (4, 16), (5, 25), (3, 9), (7, 49), (2, 4)}

In [10]:
list1= [2, 3, 4, 5, 6, 7, 8]
list2= [4, 9, 16, 25, 36, 49, 64]

pairs= {(list1[i], list2[i]) for i in range(len(list1))}


print("List 1 : ")
print(list1)
print("List 2 : ")
print(list2)
print("Output:")
print(pairs)

List 1 :
[2, 3, 4, 5, 6, 7, 8]
List 2 :
[4, 9, 16, 25, 36, 49, 64]
Output:
{(7, 49), (2, 4), (4, 16), (8, 64), (6, 36), (3, 9), (5, 25)}

Q11. Define two set A and B consisting of 5 elements. Now print the element after performing


      1.   A-B
      2.   B-A
      3.   A∩B
      4.   A∪B

In [11]:
A= {1, 2, 3, 4, 5}
B= {4, 5, 6, 7, 8}

print("Set A:", A)
print("Set B:", B)

union= A.union(B)
print("A∪B:", union)
intersection= A.intersection(B)
print("A∩B:", intersection)
diffAB= A.difference(B)
print("A-B:", diffAB)
diffBA= B.difference(A)
print("B-A:", diffBA)

Set A: {1, 2, 3, 4, 5}
Set B: {4, 5, 6, 7, 8}
A∪B: {1, 2, 3, 4, 5, 6, 7, 8}
A∩B: {4, 5}
A-B: {1, 2, 3}
B-A: {8, 6, 7}

## Object Oriented Programming Exercise 1:

[Classes and Objects in Python](https://pynative.com/python-classes-and-objects/)

[Instance variables in Python](https://pynative.com/python-instance-variables/)

Q12. Create a Vehicle class with max_speed and mileage instance attributes.

In [12]:
class Vehicle:
    def __init__(self, maxspeed, mileage):
        self.maxspeed= maxspeed
        self.mileage= mileage

    def info(self):
        print(f"Max Speed: {self.maxspeed} km/h")
        print(f"Mileage: {self.mileage} km")

v1= Vehicle(200, 15000)
v2= Vehicle(180, 20000)

print("Vehicle 1 Information:")
v1.info()
print("\nVehicle 2 Information:")
v2.info()

Vehicle 1 Information:
Max Speed: 200 km/h
Mileage: 15000 km

Vehicle 2 Information:
Max Speed: 180 km/h
Mileage: 20000 km

Q13. Create a child class Bus that will inherit all of the variables and methods of the Vehicle class.

Create a Bus object that will inherit all of the variables and methods of the parent Vehicle class and display it.

In [13]:
class Vehicle:
    def __init__(self, make, model, year):
        self.make= make
        self.model= model
        self.year= year

    def info(self):
        return f"{self.year} {self.make} {self.model}"

class Bus(Vehicle):
    def __init__(self, make, model, year, capacity):
        super().__init__(make, model, year)
        self.capacity= capacity

    def info(self):
        base= super().info()
        return f"{base}, Capacity: {self.capacity} passengers"

bus = Bus("Tata", "Bus", 2024, 20)
print(bus.info())

2024 Tata Bus, Capacity: 20 passengers

### Class Inheritance

Q14. Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.

Use the following code for your parent Vehicle class.

    class Vehicle:
      def __init__(self, name, max_speed, mileage):
          self.name = name
          self.max_speed = max_speed
          self.mileage = mileage

      def seating_capacity(self, capacity):
          return f"The seating capacity of a {self.name} is {capacity} passengers"

Expected Output:

    The seating capacity of a bus is 50 passengers

In [14]:
class Vehicle:
    def __init__(self, name, maxspeed, mileage):
        self.name = name
        self.maxspeed = maxspeed
        self.mileage = mileage

    def capacity(self, capacity):
        return f"The seating capacity of a bus is {capacity} passengers"

class Bus(Vehicle):
    def __init__(self, name, maxspeed, mileage):
        super().__init__(name, maxspeed, mileage)

    def capacity(self, capacity=50):
        return super().capacity(capacity)

bus= Bus("Bus", 120, 15000)
print(bus.capacity())

The seating capacity of a bus is 50 passengers

Q15. Create a Bus subclass that inherits from the Vehicle class. By default, the fare for any vehicle is calculated as the seating capacity multiplied by 100. For instances of the Bus class, an additional 10% maintenance fee should be applied to the total fare. Therefore, the final fare for a bus instance will be the sum of the total fare plus an additional 10% of that total fare.

Note: The bus has a seating capacity of 50, so the final fare amount should be 5500. You need to override the fare() method from the Vehicle class in the Bus class.

Use the provided code for the parent Vehicle class. You should access the parent class within a method of the child class.

    class Vehicle:
      def __init__(self, name, mileage, capacity):
        self.name = name
        self.mileage = mileage
        self.capacity = capacity

      def fare(self):
        return self.capacity * 100

    class Bus(Vehicle):
        pass
        School_bus = Bus("School Volvo", 12, 50)
        print("Total Bus fare is:", School_bus.fare())

    Expected Output:

    Total Bus fare is: 5500.0

In [15]:
class Vehicle:
    def __init__(self, name, mileage, capacity):
        self.name= name
        self.mileage= mileage
        self.capacity= capacity

    def fare(self):
        return self.capacity*100

class Bus(Vehicle):
    def fare(self):
        basefare= super().fare()
        maintenance= 0.10*basefare
        total= basefare+ maintenance
        return total

schoolbus= Bus("School Bus", 12, 50)
print("Total Bus fare is:", schoolbus.fare())

Total Bus fare is: 5500.0

### Python JSON Exercise
Refer: [Python JSON tutorials](https://pynative.com/python/json/)

Q16. Convert the following dictionary into JSON format

    data = {"key1" : "value1", "key2" : "value2"}
    data = {"key1" : "value1", "key2" : "value2"}

In [16]:
import json

data= {"key1": "value1", "key2": "value2"}
json= json.dumps(data)
print(json)

{"key1": "value1", "key2": "value2"}

Q17. Sort JSON keys in and write them into a file

    sampleJson = {"id" : 1, "name" : "value2", "age" : 29}

    {
          "age": 29,
          "id": 1,
          "name": "value2"
    }

In [17]:
import json
sample= {"id": 1, "name": "value2", "age": 29}
sorted= json.dumps(sample)

with open('sorteddata.json', 'w') as file:
    file.write(sorted)
print(sorted)

{"id": 1, "name": "value2", "age": 29}